<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="vignesh" failures="1" tests="5" name="4" time="0.043" errors="0" timestamp="2025-06-27T15:07:19 IST">
  <testcase classname="Pack2.Test4" name="DemoS" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Pack2.Test4.DemoS(Test4.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- DemoS -->
  <testcase classname="Pack2.Test4" name="Xe" time="0.002"/>
  <testcase classname="Pack2.Test4" name="before2" time="0.002"/>
  <testcase classname="Pack2.Test4" name="CarLoan" time="0.003"/>
  <testcase classname="Pack2.Test4" name="Ze" time="0.002"/>
</testsuite> <!-- 4 -->
